
LogPath = "logs/log.txt"
TokenSecret = "unicornsAreAwesome"
TokenExpiredIn = 1296000 

[App]
Host = "0.0.0.0"
Port = 8080

[Database]
Type = "mysql"
UserName = "root"
Password = ""
Host = "localhost:3306"
DatabaseName = "codexx"
LogPath = "logs"
EnableCache = true

[File]
UploadPath = "./upload"

[CORS]
Enable = true
Origins = "*"
Headers = "X-Requested-With, Content-Type, Content-Length, Authorization"
Methods = "GET,POST,PUT,DELETE"